services:
  - type: web
    name: nlp-on-tweets
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python ml/backend/manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
